### ISSUE TITLE
Recommendation for QC of distortion correction?

### ISSUE THREAD

**Issue by dpagliaccio** [DCAN-Labs/abcd-hcp-pipeline#53]
Hello
I was just wondering if you had or could recommend a method for checking the quality/success of the bold distortion correction step? This does not appear to be shown in the executive summary QC as it is for fMRIprep - are there other files or output that would be useful to look at?
Thanks!

**Comment by arueter1** [comment]
Hi @dpagliaccio - Thanks for the question! We will get back to you as soon as we are able. I am not sure if this is helpful to get started, but you can read more about the collection at this link: https://collection3165.readthedocs.io/en/stable/

**Comment by ericfeczko** [comment]
Hi David!

We do not provide an output for checking the degree of distortion in the executive summary QC by overlaying the two bold images (distorted and undistorted as in fmriprep). I've personally found it more helpful to simply examine the T1/bold alignment to make sure that the rigid-body registration was successful -- if not, 99 percent of the time the distortion correction is causing problems.

One can dig into the HCP-style outputs to examine the undistorted and distorted images directly -- however, we don't have those available for the derivative outputs due to the immense size required for all images -- sorry!
