### ISSUE TITLE
Clarification for filtered timeseries dtseries and mask data

### ISSUE THREAD

**Issue by aporter1350** [DCAN-Labs/abcd-hcp-pipeline#84]
I am interested in using the concatenated functional dense time series data (sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_bold_desc-filtered_timeseries.dtseries.nii) however before proceeding I was wondering if this file had been censored using filtered FD and if so is there more information regarding the threshold for censoring or is it simply the data right after stage 3 DBP Motion Censoring? There is also a .mat file (sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_desc-filtered_motion_mask.mat), is this mask created using fFD or FD? Thank you in advance for your time!

**Comment by perronea** [comment]
The dense time series has not been censored in any way. We provide the motion_mask.mat file so that researchers can censor the dtseries at whatever threshold they see fit.

Could you clarify what you mean by fFD?

**Comment by ericfeczko** [comment]
I think fFD refers to "filtered" framewise displacement, where the notch filtered was applied to the motion estimates. 

@aporter1350 Anders is right, we do not filtered the dtseries. The .mat file contains multiple FD thresholds, so that the user can pick the threshold they prefer. That being said, when we denoise and filter the timeseries signals (i.e. not the motion trace) we apply a 0.3 FD threshold and interpolate frames in excess of 0.3 FD -- this is only done when performing the denoising itself to ensure that poor quality frames do not cause artifact to leak into the denoising process.

**Comment by aporter1350** [comment]
@ericfeczko Does that mean you put back in the original data at the interpolated frames after denoising? Or does the denoised data include interpolated frames using the FD rather than fFD method? We're mostly wondering because we'd prefer to use the fFD method, given Fair et al 2020 (https://www.sciencedirect.com/science/article/pii/S1053811919309917?via%3Dihub#sec3), but don't want to risk including a large amount of interpolated data in our final correlation measures

**Comment by madisoth** [comment]
Hi, to follow up on this late, the denoised data indeed include the interpolated frames, with the thresholding based on the fFD.
